// Copyright 2026 the Exedra Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Building elements and the centreline topology around them.
//!
//! An [`Element`] is the unit of construction and the unit of invalidation:
//! a wall, a rafter, a voussoir, a sill. Its *key* is its identity — stable
//! across re-evaluations, chosen by the frontend, and the seed of the
//! [`exedra_assembly::InstancePath`] it lowers to. Handles like
//! [`crate::ElementId`] are per-construction indices and are never identity.
//!
//! Elements carry two geometric statements that must agree:
//!
//! - an [`OrientedBox`] **extent**, the analytic claim contact and load-path
//!   validation is made about, and
//! - an optional [`Part`], the constructive recipe that actually compiles to
//!   geometry, placed by the extent's own frame.
//!
//! [`Element::new`] derives the part from the extent so the two start out as
//! one expression; rules then edit the recipe (a seat, a void, a housing)
//! while the extent keeps stating what the element structurally *is*.
//!
//! [`Member`]s give an element a centreline between two [`Node`]s. Not every
//! element has one — masonry and roof skins do not — but every element that
//! participates in a member/member fit must.

use alloc::string::{String, ToString};

use exedra_constructive::builders;
use exedra_constructive::ir::{CapMode, NodeKind, Placement3, Recipe, RecipeBuilder};

use crate::evidence::Evidence;
use crate::geometry::{OrientedBox, Vec3};

/// The default material slot a derived part declares.
pub const DEFAULT_SLOT: &str = "surface";

/// Where an element came from.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum ElementOrigin {
    /// Authored directly into the construction by the frontend.
    Authored,
    /// Generated by a rule application, named by its key.
    Generated(String),
}

/// The geometry-bearing side of an element: a constructive recipe plus the
/// material slot its key binds to.
///
/// The recipe is expressed in the element's *local* frame — the same frame
/// its [`OrientedBox`] extent defines — so part edits, tool solids, and
/// contact anchors all read in one coordinate system. Lowering places the
/// part with [`OrientedBox::placement`]; there is no second placement to
/// keep in sync.
#[derive(Clone, Debug)]
pub struct Part {
    /// The constructive recipe, in element-local coordinates.
    pub recipe: Recipe,
    /// The material slot [`Element::material`] binds to.
    pub slot: String,
}

impl Part {
    /// Wraps a recipe, binding [`DEFAULT_SLOT`].
    #[must_use]
    pub fn new(recipe: Recipe) -> Self {
        Self {
            recipe,
            slot: DEFAULT_SLOT.to_string(),
        }
    }

    /// Binds a different material slot. The slot must be declared by the
    /// recipe or lowering reports it.
    #[must_use]
    pub fn with_slot(mut self, slot: &str) -> Self {
        self.slot = slot.to_string();
        self
    }

    /// The recipe for a solid box of `size` at the local origin, tagged with
    /// the opaque source reference `source`.
    ///
    /// This is the default part [`Element::new`] derives from an extent: the
    /// smallest honest recipe that fills the declared extent exactly. It is
    /// sugar over [`exedra_constructive::builders::rect`], not a shape
    /// library — `joiner` grows no catalogue of profiles.
    ///
    /// Returns `None` when `size` is not strictly positive and finite.
    #[must_use]
    pub fn boxed(size: Vec3, source: &str) -> Option<Recipe> {
        if !size.iter().all(|value| value.is_finite() && *value > 0.0) {
            return None;
        }
        let mut builder = RecipeBuilder::new();
        let source = builder.source_ref(source);
        let slot = builder.material_slot(DEFAULT_SLOT);
        let profile = builder.add_profile(builders::rect(size[0], size[1]).ok()?);
        let node = builder
            .with_source(source)
            .with_material(slot)
            .add(NodeKind::Extrude {
                profile,
                placement: Placement3::IDENTITY,
                height: size[2],
                caps: CapMode::Both,
            })
            .ok()?;
        builder.finish(node).ok()
    }
}

/// One building element.
///
/// Fields are public because an element is a record, not a machine: it holds
/// no invariant a setter could protect that [`crate::validate()`] does not
/// already report by key. The one field a frontend does not set is
/// [`Element::origin`], which [`crate::Construction::apply`] stamps on the
/// parts a rule generates.
#[derive(Clone, Debug)]
pub struct Element {
    /// Stable frontend-supplied identity. Non-empty, free of `/`, and unique
    /// among elements.
    pub key: String,
    /// Opaque frontend role label (`"tie-beam"`, `"voussoir"`, `"sill"`).
    /// `joiner` never interprets it; it reaches the assembly as instance
    /// metadata.
    pub role: String,
    /// Opaque material key bound to the part's slot.
    pub material: String,
    /// The declared structural extent.
    pub extent: OrientedBox,
    /// The compiled geometry, or `None` for an element that bears none.
    pub part: Option<Part>,
    /// What this element's presence and placement is based on.
    pub evidence: Evidence,
    /// How many *distinct* directly supporting elements this element must
    /// have for the hypothesis to stand. Zero means "any route to ground
    /// will do".
    pub required_supports: usize,
    /// Whether this element must own a centreline [`Member`]. Elements that
    /// participate in member/member fits do; surfaces and mass do not.
    pub requires_member: bool,
    /// Whether the element is part of the current hypothesis. Omitting an
    /// element keeps its key and its relations in the graph while removing
    /// it from geometry, contact witnesses, and load paths — that is how a
    /// "what if this timber was never there" question is asked.
    pub present: bool,
    /// Authored, or generated by a named rule application.
    pub origin: ElementOrigin,
}

impl Element {
    /// A present, authored element filling `extent` with a derived box part.
    ///
    /// The derived part's source reference is `joiner:element/<key>`.
    #[must_use]
    pub fn new(
        key: &str,
        role: &str,
        material: &str,
        extent: OrientedBox,
        evidence: Evidence,
    ) -> Self {
        let part = Part::boxed(extent.size, &alloc::format!("joiner:element/{key}")).map(Part::new);
        Self {
            key: key.to_string(),
            role: role.to_string(),
            material: material.to_string(),
            extent,
            part,
            evidence,
            required_supports: 0,
            requires_member: false,
            present: true,
            origin: ElementOrigin::Authored,
        }
    }

    /// Requires `count` distinct directly supporting elements.
    #[must_use]
    pub fn with_required_supports(mut self, count: usize) -> Self {
        self.required_supports = count;
        self
    }

    /// Declares that this element must own a centreline member.
    #[must_use]
    pub fn with_member(mut self) -> Self {
        self.requires_member = true;
        self
    }

    /// Replaces the derived part.
    #[must_use]
    pub fn with_part(mut self, part: Part) -> Self {
        self.part = Some(part);
        self
    }

    /// Drops the geometry: the element stays in the graph and in the load
    /// path but lowers to no instance.
    #[must_use]
    pub fn without_part(mut self) -> Self {
        self.part = None;
        self
    }
}

/// A named point in the centreline topology.
#[derive(Clone, Debug, PartialEq)]
pub struct Node {
    /// Stable frontend-supplied identity, unique among nodes.
    pub key: String,
    /// World-space position, in meters.
    pub point: Vec3,
}

impl Node {
    /// A node at `point`.
    #[must_use]
    pub fn new(key: &str, point: Vec3) -> Self {
        Self {
            key: key.to_string(),
            point,
        }
    }
}

/// An element's centreline, between two nodes.
///
/// Members are what member/member relations name, so a fit can be stated
/// between *lines* rather than between solids: the solids are consequences.
#[derive(Clone, Debug)]
pub struct Member {
    /// Stable frontend-supplied identity, unique among members. Members may
    /// share a key with the element they belong to; the two namespaces are
    /// separate.
    pub key: String,
    /// The [`Element::key`] this centreline belongs to.
    pub element: String,
    /// Start [`Node::key`]; must lie inside the element's extent.
    pub from: String,
    /// End [`Node::key`]; must lie inside the element's extent.
    pub to: String,
    /// What this centreline is based on.
    pub evidence: Evidence,
}

impl Member {
    /// A centreline for `element` from `from` to `to`.
    #[must_use]
    pub fn new(key: &str, element: &str, from: &str, to: &str, evidence: Evidence) -> Self {
        Self {
            key: key.to_string(),
            element: element.to_string(),
            from: from.to_string(),
            to: to.to_string(),
            evidence,
        }
    }
}

/// Which translations a support restrains.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct Restraints {
    /// Restrained translation along world x, y, z.
    pub translation: [bool; 3],
}

impl Restraints {
    /// All three translations restrained.
    pub const FIXED: Self = Self {
        translation: [true, true, true],
    };
}

/// Where an element's load leaves the model.
#[derive(Clone, Debug)]
pub struct Support {
    /// Stable frontend-supplied identity, unique among supports.
    pub key: String,
    /// The supported [`Element::key`].
    pub element: String,
    /// Opaque name of what supports it (`"ground"`, `"crypt-vault"`).
    pub ground: String,
    /// Which translations are restrained; at least one must be.
    pub restraints: Restraints,
}

impl Support {
    /// A fully restrained support for `element` on `ground`.
    #[must_use]
    pub fn fixed(key: &str, element: &str, ground: &str) -> Self {
        Self {
            key: key.to_string(),
            element: element.to_string(),
            ground: ground.to_string(),
            restraints: Restraints::FIXED,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evidence::EvidenceClass;

    fn evidence() -> Evidence {
        Evidence::new("fixture", EvidenceClass::ModernEngineeringInference)
    }

    #[test]
    fn a_new_element_derives_a_part_that_fills_its_extent() {
        let element = Element::new(
            "tie-beam",
            "tie-beam",
            "oak",
            OrientedBox::axis_aligned([0.0; 3], [4.0, 0.3, 0.3]),
            evidence(),
        );
        let part = element
            .part
            .as_ref()
            .expect("positive extent derives a part");
        assert_eq!(part.slot, DEFAULT_SLOT);
        assert_eq!(part.recipe.slots(), &[DEFAULT_SLOT.to_string()]);
        assert_eq!(
            part.recipe.sources(),
            &["joiner:element/tie-beam".to_string()]
        );
        assert_eq!(element.origin, ElementOrigin::Authored);
        assert!(element.present);
    }

    #[test]
    fn a_degenerate_extent_derives_no_part_instead_of_panicking() {
        let element = Element::new(
            "sliver",
            "sliver",
            "oak",
            OrientedBox::axis_aligned([0.0; 3], [0.0, 1.0, 1.0]),
            evidence(),
        );
        assert!(element.part.is_none(), "zero extent yields no recipe");
        assert!(Part::boxed([f64::NAN, 1.0, 1.0], "x").is_none());
    }

    #[test]
    fn builder_methods_stay_chainable() {
        let element = Element::new(
            "rafter",
            "rafter",
            "oak",
            OrientedBox::axis_aligned([0.0; 3], [1.0, 1.0, 1.0]),
            evidence(),
        )
        .with_required_supports(2)
        .with_member()
        .without_part();
        assert_eq!(element.required_supports, 2);
        assert!(element.requires_member);
        assert!(element.part.is_none());
    }
}
