[package]
name = "exedra_render_bench"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Simple executable benchmarks for exedra render extraction"
keywords = ["benchmark", "mesh", "render-extraction"]
categories = ["algorithms"]

[lints]
workspace = true

[dependencies]
exedra = { features = ["std"], workspace = true }
exedra_fidget = { features = ["std"], workspace = true }
exedra_isosurface = { features = ["std"], workspace = true }
exedra_primitives = { features = ["std"], workspace = true }
exedra_qef = { features = ["std"], workspace = true }
exedra_spatial = { workspace = true }
fidget.workspace = true
