// Copyright 2026 the Exedra Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

use crate::profile::{Loop2, Profile2, ProfileError, Seg2, SegTag};
use alloc::vec::Vec;
use exedra_math::Placement3;
use exedra_mesh::FaceId;
use exedra_mesh_ops::section as geometry;

/// One section region converted to an owned, reusable profile.
///
/// Segment tags index [`Self::segment_sources`], numbered across the outer
/// loop followed by the holes. Tags remain useful after deliberate seam changes
/// that preserve them. They are local to this result, not persistent face
/// selectors or inferred correspondence with another profile.
///
/// Sources are copied from the section: mesh [`FaceId`]s or constructive
/// [`Feature`](crate::tessellate::Feature)s. Keep the originating mesh/body or
/// snapshot identity when interpreting them; conversion cannot detect later
/// source edits. The profile and placement can be reused without that source.
#[derive(Clone, Debug, PartialEq)]
pub struct SectionProfile<S> {
    /// Polyline profile with the original outer boundary and holes.
    pub profile: Profile2,
    /// Section-local XY to source mesh/body coordinates, copied unchanged.
    /// Extrusion along local +Z follows the section plane's positive normal.
    pub placement: Placement3,
    /// Source for each generated segment tag, in outer-then-hole order.
    /// Editing this table or replacing tags changes their correspondence.
    pub segment_sources: Vec<S>,
}

impl<S> SectionProfile<S> {
    /// Looks up a tag generated by this conversion.
    ///
    /// Returns `None` for an index outside this result's source table. This
    /// lookup does not establish that a tag came from this particular profile
    /// or that its original mesh/body is still current.
    #[must_use]
    pub fn source(&self, tag: SegTag) -> Option<&S> {
        self.segment_sources.get(tag.0 as usize)
    }
}

/// Refusal to convert a section; no partial list of profiles is returned.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub enum SectionProfileError {
    /// The frame is nonfinite, singular, left-handed, or has a nonfinite determinant.
    InvalidFrame,
    /// A boundary has fewer than three points, or zero/nonfinite signed area.
    InvalidBoundary {
        /// Index in the section's region list.
        region: usize,
        /// Zero for the outer loop; `1 + i` for hole `i`.
        loop_index: usize,
    },
    /// The source table does not name exactly one source per boundary edge.
    SourceCount {
        /// Index in the section's region list.
        region: usize,
        /// Zero for the outer loop; `1 + i` for hole `i`.
        loop_index: usize,
        /// Number of cyclic boundary points (and therefore edges).
        points: usize,
        /// Number of supplied sources.
        sources: usize,
    },
    /// Profile construction failed, including exhaustion of the u32 tag space.
    InvalidProfile {
        /// Index in the section's region list.
        region: usize,
        /// The underlying profile requirement that was violated.
        error: ProfileError,
    },
}

impl core::fmt::Display for SectionProfileError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidFrame => {
                f.write_str("section profile requires a finite right-handed frame")
            }
            Self::InvalidBoundary { region, loop_index } => {
                write!(
                    f,
                    "section region {region}, loop {loop_index} has invalid polygon geometry"
                )
            }
            Self::SourceCount {
                region,
                loop_index,
                points,
                sources,
            } => write!(
                f,
                "section region {region}, loop {loop_index} has {points} edges but {sources} sources"
            ),
            Self::InvalidProfile { region, error } => write!(f, "section region {region}: {error}"),
        }
    }
}

impl core::error::Error for SectionProfileError {
    fn source(&self) -> Option<&(dyn core::error::Error + 'static)> {
        match self {
            Self::InvalidProfile { error, .. } => Some(error),
            _ => None,
        }
    }
}

/// Converts a mesh plane section into one profile per filled region.
///
/// This is the same conversion as constructive
/// [`PlaneSection::to_profiles`](crate::section::PlaneSection::to_profiles),
/// with source face IDs instead of construction features. No mesh traversal or
/// tessellation occurs. An empty section returns an empty vector. Coordinates,
/// cyclic starting points, winding, collinear samples, hole order and region
/// order are preserved; no curves or loft correspondence are inferred.
///
/// Section extraction establishes simplicity, separation and nesting. Callers
/// editing the public section fields must preserve those properties. Conversion
/// applies the ordinary [`Loop2::new`] and [`Profile2::new`] checks; it does not
/// certify section topology or repeat extraction's budgeted intersection checks.
///
/// # Errors
/// Rejects invalid frames, malformed boundary/source arrays, degenerate polygon
/// area, unrepresentable segment tags, and ordinary profile construction failures.
pub fn profiles_from_mesh_section(
    section: &geometry::PlaneSection,
) -> Result<Vec<SectionProfile<FaceId>>, SectionProfileError> {
    check_frame(section.frame)?;
    section
        .regions
        .iter()
        .enumerate()
        .map(|(index, region)| {
            convert_region(
                section.frame,
                index,
                (&region.outer.points, &region.outer.edge_faces),
                region
                    .holes
                    .iter()
                    .map(|hole| (hole.points.as_slice(), hole.edge_faces.as_slice())),
            )
        })
        .collect()
}

pub(crate) fn check_frame(frame: Placement3) -> Result<(), SectionProfileError> {
    let determinant = frame.linear_determinant();
    if !frame.is_finite() || !determinant.is_finite() || determinant <= 0.0 {
        return Err(SectionProfileError::InvalidFrame);
    }
    Ok(())
}

pub(crate) fn convert_region<'a, S: Clone + 'a>(
    placement: Placement3,
    region: usize,
    outer: (&[[f64; 2]], &[S]),
    holes: impl Iterator<Item = (&'a [[f64; 2]], &'a [S])>,
) -> Result<SectionProfile<S>, SectionProfileError> {
    let invalid_profile = |error| SectionProfileError::InvalidProfile { region, error };
    let mut segment_sources = Vec::new();
    let mut convert_loop = |loop_index, points: &[[f64; 2]], sources: &[S]| {
        if points.len() != sources.len() {
            return Err(SectionProfileError::SourceCount {
                region,
                loop_index,
                points: points.len(),
                sources: sources.len(),
            });
        }
        if points.len() < 3 {
            return Err(SectionProfileError::InvalidBoundary { region, loop_index });
        }
        let mut segments = Vec::with_capacity(points.len());
        for (i, source) in sources.iter().enumerate() {
            let tag = u32::try_from(segment_sources.len())
                .map_err(|_| invalid_profile(ProfileError::TooManySegments))?;
            let to = points[(i + 1) % points.len()];
            segments.push(Seg2::line((to[0], to[1])).tagged(SegTag(tag)));
            segment_sources.push(source.clone());
        }
        let boundary = Loop2::new(segments).map_err(invalid_profile)?;
        let area = boundary.signed_area();
        if !area.is_finite() || area == 0.0 {
            return Err(SectionProfileError::InvalidBoundary { region, loop_index });
        }
        Ok(boundary)
    };
    let outer = convert_loop(0, outer.0, outer.1)?;
    let holes = holes
        .enumerate()
        .map(|(i, (points, sources))| convert_loop(i + 1, points, sources))
        .collect::<Result<Vec<_>, _>>()?;
    let profile = Profile2::new(outer, holes).map_err(invalid_profile)?;
    Ok(SectionProfile {
        profile,
        placement,
        segment_sources,
    })
}

#[cfg(test)]
mod tests;
