[package]
name = "exedra"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Structural half-edge mesh kernel"
keywords = ["mesh", "half-edge", "topology", "no_std"]
categories = ["data-structures", "algorithms"]

[dependencies]
exedra_triangulate.workspace = true
hashbrown.workspace = true
invalidation.workspace = true
libm = { optional = true, workspace = true }

[features]
default = ["std"]
libm = ["dep:libm"]
std = []

[dev-dependencies]
exedra_testkit = { features = ["std"], workspace = true }

[lints]
workspace = true
